# **Numpy**

# **What is Numpy ?**
- The numpy stands for Numerical python.
- numpy is the library in python, used for mathematical calculations.
- It provide support for large multi-dimensional **arrays** and matrices.

# Data structures in numpy
**1.N-dimensional array(n-D array):**
- The n-D array have N dimensions.
- n-D array can represent Vectors(1-D array),matrices(2-D array), or tensors(3-D array).
- The n-D array are homogeneous(It contain only similar type of data).
- n-D array are have fixed size.once we created we cannot change size of this array.

**2.Structured array**:
- It is also known as **Record array**.
- structured array are heterogeneous array, i.e it stores the different types of data.

**Masked array**:
- These arrays are useful to deal with datasets contaning missing values,invalid data or placeholder.

# **Data types in structured arrays.**

**1.'i' or 'i4'**: It used as integer(int).

**2.'U10'** : It is used as a string(str).

**3. 'f' or 'f8'** : It is used as a float.

**4.'bool'** : It is used as a boolean.i.e give  output as true /false.

# **Vectors** 
- It is  one dimensional array (1-D array).

# **Matrix**
- It is also known as **2-D tensor**. i.e arrays with rows  columns.

# **Tensor**
- It is known as n-D array.i.e it have 3 or more dimensions.


# How to import numpy ?
- use **import numpy as np**

**import library**

In [10]:
import numpy as np

**Q.1 create a 2D array of shape(3,4) filled with all 1s.**

**1.ones**: ***To create an array filled with 1. mention the shape of array.(rows,column)***

In [13]:
a= np.ones((3,4)) # it craete array filled with all 1s 
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


**Q.2 create a 1D numpy array with values from 10 to 25 with a step of 4.**

**2.arange** : ***To create an array with evenly specified in the range.***

In [16]:
b=np.arange(10,25,4) # to arrange the matrix use arange(start,stop,step).create an array with  evenly specified in the range
print(b)            # it display in integer value

[10 14 18 22]


**Q.3 Create a 4x4 identity matrix.**

**3.identity** : ***It use **eye()** method To create identity matrix(specify number of rows).***


In [19]:
c=np.eye(4) # to create identity matrix(specify number of rows)
print(c)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**Q.4 create an array with 5 values evenly spaced between 0 and 1.**

**4.linspace** : ***Create an array of evenly spaced number(specified interval-(display in float)).***

In [22]:
d=np.linspace(0,1,5) # create an array of evenly spaced number(specified interval-(display in float)) linspace(start,stop,step)
print(d)

[0.   0.25 0.5  0.75 1.  ]


**Q.5 create a 1D numpy array with values from 10 to 50 with a step of 5.**

In [24]:
e=np.arange(10,50,5) # to arrange the matrix use arange(start,stop,step).create an array with  evenly specified in the range
print(e)

[10 15 20 25 30 35 40 45]


**Q.6 craete a 3X3 array with random integer between 10 and 99.** 

**5.size**: ***To give size of array.***

In [27]:
f=np.random.randint(10,99,size=(3,3)) # random.randint () use for it select number in randomly.
print(f)

[[65 45 64]
 [91 76 17]
 [64 62 55]]


**Q.7 create an array of shape(2,3) filled with zeros,and another filled with sevens.**

In [29]:
zero_array=np.zeros((2,3)) # to filled with zeros.

sevens_array=np.full((2,3),7) # full() use to filled with any number except 1 or 0
print("Zero array is:\n",zero_array)
print("Sevens array is:\n",sevens_array)

Zero array is:
 [[0. 0. 0.]
 [0. 0. 0.]]
Sevens array is:
 [[7 7 7]
 [7 7 7]]


**Q.8 Create an array with values from 1 to 12 and reshape it to a 3X4 matrix.** 

In [31]:
h=np.arange(1,13).reshape(3,4) #  reshape use for it rearrange the element to fit in new shape. 
print(h)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


**Q.9 Create a 2D array of shape (5,2) and display its attributes.**

In [33]:
p=np.random.randint(1,15,size=(5,2)) # create array it take random numbers between 1 to 15
print(p)

p.ndim # to find dimension of array
print("Dimensions of array is:",p.ndim)

p.shape # to find shape of an array
print("The shape of array is:",p.shape)

p.dtype # to get data type of elements in array
print("The Data type of array is:",p.dtype)







[[ 7  7]
 [ 3 11]
 [ 5  9]
 [11  1]
 [12 10]]
Dimensions of array is: 2
The shape of array is: (5, 2)
The Data type of array is: int32


**Q.10 create a 2D array and access its element.first element,second element , last element.**

In [35]:
x = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]]) # create 2D array

print("First row:", x[0]) # to get first element in array
print("Second column:", x[:, 1])  # to get second element in the array
print("Last element:", x[-1, -1]) # to get last elements in the array (-1 for last rows,and last column)


First row: [10 20 30]
Second column: [20 50 80]
Last element: 90


**Q.1 Create a 1D array of numbers from 0 to 9.**

In [37]:
array1=np.arange(0,9)
print(array1)

[0 1 2 3 4 5 6 7 8]


**Q.2 Find the mean, median, standard deviation, and sum of elements in an array.**

# Mathematical operation on arrays

**1.mean()**: ***To find mean(average) of all the items.***

**2.std()** : ***To find standard deviation of the all items.***

**3.median()** : ***To find median of items.***

**4.sum()**: ***To find sum(total) of all items.***

**5.min()** : ***To find minimum value in items.***

**6.max()** : ***To find maximum value in items.***

**7.argmax()** :***It return index value of max value.***

**8.argmin()** :***It return index value of min value.***

In [40]:
arr=np.array([10,20,30,40,50,60])
print(arr)

print("Mean",np.mean(arr)) # to find mean(average) of all items
print("Median :",np.std(arr)) # to find standard deviation of all items
print("standard deviation:",np.sum(arr)) # to get sum(total) of all items
print("Median:",np.median(arr)) # to get median of all items

[10 20 30 40 50 60]
Mean 35.0
Median : 17.07825127659933
standard deviation: 210
Median: 35.0


**Q.3 Find the maximum and minimum values in an array and their indices.**

In [42]:
arr=np.array([10,20,30,40,50,60])
print(arr)

print("Min:",np.min(arr)) # to get min value of items
print("Max:",np.max(arr)) # to get max value of items
 
print("Index of min value:",np.argmin(arr)) # to get index value of min value
print("Index of max value:",np.argmax(arr)) # to get index value of max value

[10 20 30 40 50 60]
Min: 10
Max: 60
Index of min value: 0
Index of max value: 5


# Random Number Methods

**1.random.randint()** : ***generate  and return an array of the given size,and the number in th range.***

**2.random.rand(size)** : ***use  return in float,it return 1D array with randomvalues in the range (0-1).***

**3.random.randn(rows,column)** : ***value range is(-infinity to +infinity)  each element mean is 0 and SD=1 .***

**Q.4 Generate a 1D array of 10 random integers between 1 and 100.**

In [45]:
random_array=np.random.randint(1,101,10) # to random number in the range
print(random_array)

[29 39 19 88 32 16 13 89 90 10]


**Q.5 Create a 3x3 array of random floats.**

In [47]:
rand_array=np.random.randn(3,3) # to get random float array it  also include negative values range value(-infinity to +infinity),randn generate and return an array with normal distribution
print(rand_array)

[[ 0.67205489  0.5050971   0.60316209]
 [-1.20547692  2.13841487  0.02081219]
 [ 1.67535516 -0.89498074 -0.70429856]]


**Q.6 Generate 1000 samples from a normal distribution and compute mean and std.**

In [49]:
sample=np.random.randn(1000)


print("Mean:",np.mean(sample))
print("Standard deviation:",np.std(sample))

Mean: -0.01861097816906431
Standard deviation: 0.9900476451156083


# Array manipulation

**1.np.sort()** : ***Return the sorted values in the array.default sorting is in ascending order.***

**2.np.unique()** :***Return array  an sorted with unique values.***

**3.np.concatenate()** :***Return the mergerd array, can join the two or more than two array.***


**Q.7 Get unique values from an array and their counts.**

In [52]:
a=np.array([1,2,3,4,7,5,3,4])
print(a)

print("Unique values are:",np.unique(a))


[1 2 3 4 7 5 3 4]
Unique values are: [1 2 3 4 5 7]


**Q.8 Generate a 2D array of shape (5, 5) from a normal distribution with mean=50 and std=10.**

In [54]:
mean=50
std=10
v=np.random.randn(5,5) * std + mean
print(v)

[[60.67238531 50.66714504 23.05506678 55.67370939 45.94720404]
 [54.68734496 35.18594317 41.06435156 60.93938887 38.34158827]
 [60.15137739 43.55010152 45.14313248 70.48447894 49.55087627]
 [31.08797307 40.45286887 55.37698407 62.40953715 35.62525239]
 [58.03347849 48.24852119 60.90909415 43.76301157 52.90717023]]


**Q.9 Create a NumPy array of even numbers from 2 to 20.**

In [56]:
even_array=np.arange(2,20,2)
print("Even array is:",even_array)

Even array is: [ 2  4  6  8 10 12 14 16 18]


**Q.10 Find the shape, size, and data type of the array a = np.array([[1, 2], [3, 4]]).**

In [58]:
a=np.array([[1,2],[3,4]])
print("Shape of array:",a.shape) # to get shape of array
print("Size of array:",a.size) # to get size of an array 
print("Data types of array:",a.dtype) # to get data types of array




Shape of array: (2, 2)
Size of array: 4
Data types of array: int32


**Q.11 Generate a 1D array of 5 random numbers between 0 and 1.**

In [60]:
random_array=np.random.rand(5) # to random number in the range
print(random_array)

[0.51980591 0.30434891 0.13813128 0.23397164 0.77480234]


**Q.12 Find the maximum, minimum, and sum of elements in the array [5, 8, 2, 9, 1].**

In [62]:
b=np.array([5, 8, 2, 9, 1])
print("maximum item:",np.max(b)) # to get maximum item
print("minimum item:",np.min(b)) # to get minimum value
print("sum of array:",np.sum(b)) # to get sum of items

maximum item: 9
minimum item: 1
sum of array: 25


**Q.13 Get the first 3 elements from the array [10, 20, 30, 40, 50].**

In [64]:
c=np.array([10,20,30,40,50])
print("First three elements are:",c[:3]) # c[:3] it return first three element in the array

First three elements are: [10 20 30]


# Mathematical Operation on Matrix

**1.Addition**: ***Adds the corresponding elements of matrices.***

**2.Subtraction**:***Subtracts one matrix from another element wise.***

**3.multiplication**:***It multiplies every element in the matrix.***

**4.dot product**:***It multiplies the row element in first matrix to column of  second matrix.***

**5.Transpose**: ***It convert the row into the column.***

**Q.1 Given two arrays,add,subtract,mulitiply them element-wise.**

In [67]:
A=np.array([[2,5],[7,8]]) # take first array
B=np.array([[5,6],[1,3]]) #  take second array
Addition=A + B # to add two matrix
print("Addition of two matrix is:\n",Addition) 

subtraction=A - B # to subtraction of two matrix
print("Subtraction of two matrix is:\n",subtraction)

multiplication=A * B # to multiply the two matrix
print("Multiplication of two matrix is:\n",multiplication)

Addition of two matrix is:
 [[ 7 11]
 [ 8 11]]
Subtraction of two matrix is:
 [[-3 -1]
 [ 6  5]]
Multiplication of two matrix is:
 [[10 30]
 [ 7 24]]


**Q.2 create two 2X2 numpy arrays and perform matrix addition.**

In [69]:
C=np.array([[10,20],[30,40]])
D=np.array([[50,60],[70,80]])
Add=C + D # to add the element of two matrix
print("Addition of two matrix is:\n",Add)

Addition of two matrix is:
 [[ 60  80]
 [100 120]]


**Q.3 create a 2X3 matrix and 3X2 matrix, then perform matrix multiplication using numpy.**

In [71]:
matrix_1=np.array([[1,2,3],[4,5,6]]) # create 2X3 matrix
matrix_2=np.array([[2,3],[7,8],[5,9]]) # create 3X2 matrix
Mul=np.dot(matrix_1 ,matrix_2) # dot use for multiplies 
print("Multiplication is:\n",Mul)

Multiplication is:
 [[ 31  46]
 [ 73 106]]


**Q.4 create a two 3X3 matrix and subtract  the second from first.**

In [73]:
matrix_1=np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix_2=np.array([[4,5,3],[11,12,13],[14,15,16]])
Subtraction=matrix_2 - matrix_1
print("Subtraction is:\n",Subtraction)

Subtraction is:
 [[3 3 0]
 [7 7 7]
 [7 7 7]]


# Random Sampling
- It randomly picks values rom a given matrix. 
- we use **np.random.choice**, It for only rows.
- **flatten** use for to convert the 2D array into 1D array.

# Random Shuffle
- shuffle for rearange the row .
- we use **np.random.shuffle()**

**Q.5 create 1D array with values from 10 to 20.randomly pick 3 element without replacement.**

In [76]:
E=np.arange(10,21) # take array range from 10 to 20
random_array=np.random.choice(E,size=3,replace=False) # replace =False for it take element without any replacement
print(random_array)       # random.choice for to  choose the element randomly

[18 20 10]


**Q.6 create a 4X3 matrix.randomly select one of the rows.**

In [78]:
matrix=np.array([[1,2,3,4],[5,6,7,8],[9,11,12,10]])
rows=np.random.choice(matrix.shape[0],size=1,replace=False) # to  choose randomly any row
print(rows)

[2]


**Q.7 create an array with values from 1 to 10 and shuffle it in place.**

In [80]:
N=np.arange(1,11)
np.random.shuffle(N) # shuffle for rearange the row 
print(N)

[10  3  6  1  5  2  8  7  4  9]


# Comparision in numpy 
- It gives the out put in **boolean(true/false)**

**1.==** :***First matrix is equal to second matrix.***

**2.!=** : ***First matrix is not equal to second matrix.***

**3.>** : ***First matrix element is grater than second.***

**4.<** :***First matrix element is less than second matrix element.***

**5.>=** : ***First matrix element is grater than or equal to second.***

**6.<=** :***First matrix element is less than or equal to second matrix element.***

**Q.8 create two 2X2 matrices and return a boolean matrix where the first is greater than the second.**

In [83]:
P=np.array([[10,20],[30,40]])
Q=np.array([[5,6],[7,8]])
greater_matrix=P > Q # to find the first matrix is greater than second matrix
print("P is grater than Q ?\n",greater_matrix)


P is grater than Q ?
 [[ True  True]
 [ True  True]]


**Q.9 create a 3X3 matrix with reandom integer(0-20).count how many element greater than 10.**

In [85]:
M=np.random.randint(0,21,size=(3,3))
print(M)
count=np.sum(M > 10) # to count the element greater than 10
print("Count of element greater than 10 is",count)


[[10 16 20]
 [16 16  6]
 [ 6  4  9]]
Count of element greater than 10 is 4


**Q.10 convert a 2D array to a 1D array(flatten it).**

In [87]:
g=np.array([[1,2,3],[4,5,6]])
flatten_array=g.flatten() # flatten is convert to 2D array into 1D array.
print(flatten_array)

[1 2 3 4 5 6]


# Permutation in numpy
- use **np.random.permutation**
- it shuffle the element of the given range or array.return a new order./ we can arrange the element


# Permutation Vs Shuffle
**1.permutation : In permutation we can create a copy of list and arrange (shuffle) the element  without any changes in original lists.**

**2.Shuffle : The shuffle the element with changes in original lists.**

**Q.1 Given arr = np.array([1, 2, 3, 4]),shuffle the array without modifying the original.**

In [89]:
arr = np.array([1, 2, 3, 4])
print(arr)
shuffled_arr = np.random.permutation(arr)
print(shuffled_arr)

[1 2 3 4]
[2 1 3 4]


**Q.2 Write a program to: Create an array of numbers from 1 to 10.Generate a new array that is a randomly permuted version of the original.
Print both arrays to show that the original is unchanged.**

In [91]:
a = np.arange(1, 11)
print(a)

# Generate a new array that is a randomly permuted version of the original
permuted_array = np.random.permutation(a)
print("permutated array is:",permuted_array)

[ 1  2  3  4  5  6  7  8  9 10]
permutated array is: [ 5  3  9  7  6  4  8  2 10  1]


# Cumulative sum
- In numpy for cumulative sum we use **np.cumsum()**.
- It add the element to the next item and return

# Cumulative product
- In numpy for cumulative product we use **np.cumprod()**.
- It multiply the element to the next item and return

**In 2D  for rows and column**
- **1. (axis=0) column wise**     
- **2. (axis=1) row wise**

**Q.3 Write a program that: Takes a 1D NumPy array of positive integers.Calculates and prints:The cumulative sum (np.cumsum)The cumulative product (np.cumprod)**

In [93]:
# Create a 1D NumPy array of positive integers
b= np.array([1, 2, 3, 4, 5])
print(b)

# Calculate the cumulative sum
cumulative_sum = np.cumsum(b) # 1,1+2=3,3+3=6,6+4=10,10+5=15
print("Cumulative sum:", cumulative_sum)

# Calculate the cumulative product
cumulative_product = np.cumprod(b)
print("Cumulative product:", cumulative_product)

[1 2 3 4 5]
Cumulative sum: [ 1  3  6 10 15]
Cumulative product: [  1   2   6  24 120]


**Q.4 Take a 3D array, Write a program to compute: Cumulative sum along axis 0 . Cumulative product along axis 1**

In [95]:
# Create a 3D NumPy array
c = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
    [[19, 20, 21], [22, 23, 24], [25, 26, 27]]
])
print(c)
# Compute the cumulative sum along axis 0
cumulative_sum = np.cumsum(c, axis=0)

print("\nCumulative sum along axis 0:")
print(cumulative_sum)

# Compute the cumulative product along axis 1
cumulative_product = np.cumprod(c, axis=1)
print("\nCumulative product along axis 1:")
print(cumulative_product)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]

Cumulative sum along axis 0:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 13 15]
  [17 19 21]
  [23 25 27]]

 [[30 33 36]
  [39 42 45]
  [48 51 54]]]

Cumulative product along axis 1:
[[[    1     2     3]
  [    4    10    18]
  [   28    80   162]]

 [[   10    11    12]
  [  130   154   180]
  [ 2080  2618  3240]]

 [[   19    20    21]
  [  418   460   504]
  [10450 11960 13608]]]


# logical condition in numpy
**1.and**: 
- use np.logical_and(conditions).
- use and condition it return true only if the both condition are true

**2.or**: 
- use np.logical_or(conditions)
- use or condition ,it return true when one condition is true.

**3.not**:
- use np.logical_not(conditions).
- it reverse the output **true->false** and **false->true**

**4.any**:
- use np.any(condition).
- if any one element  is true then it return true.

**5.all**:
- use np.all(condition).
- all condtion are met(true) then return true

# Filtering in numpy
- works as logical and instead of returning boolean values it return real values

**1. & (and)**: 
- Return the element that meets both the specified condition

**2.| (or)**:
- Return the element that meets either one of the specified condiotion.

**3.~ (not)**:
- Return the element which meets the opposite condition of the specified condition

**4.where**:
- It return the index base on the condition.



**Q.5 Take an array of student scores and Write a program to: Print all scores greater than 60 and less than 85.
Replace all scores less than 50 with 0 using logical indexing.**

In [97]:
# Create an array of student scores
scores = np.array([45, 66, 80, 35, 70, 95, 56, 49, 75, 82])

# Print all scores greater than 60 and less than 85
print("Scores between 60 and 85:")
print(scores[(scores > 60) & (scores < 85)])

# Replace all scores less than 50 with 0 using logical indexing
scores[scores < 50] = 0
print("\nUpdated scores:")
print(scores)

Scores between 60 and 85:
[66 80 70 75 82]

Updated scores:
[ 0 66 80  0 70 95 56  0 75 82]


# percentile and Quantile
- In percentile we mostly use 25 th,50 th,75 th percentile. we use **np.percentile()**
- For quantile we give value in float(0.25). use **np.quantile()**

**Q.6 6. Take an array a = [12,15,16,22,21,35,65,70,85,100,40]. Write a program to: Compute the median . Compute the 25th, 50th, and 75th percentiles
Compute the 0.1, 0.5, and 0.9 quantiles.**

In [141]:
# Create an array
a = np.array([12, 15, 16, 22, 21, 35, 65, 70, 85, 100, 40])

# Compute the median
median = np.median(a)
print("Median:", median)
print("The 25 th percentile is:",np.percentile(a,25))
print("The 50 the percentile is:",np.percentile(a,50)) 
print("The 75 th percentile is:",np.percentile(a,75))

print("The quantile of 0.1 is:",np.quantile(a,0.1)) 
print("The quantile of 0.5 is:",np.quantile(a,0.5)) 
print("The quantile 0.9 is:", np.quantile(a,0.9)) 



Median: 35.0
The 25 th percentile is: 18.5
The 50 the percentile is: 35.0
The 75 th percentile is: 67.5
The quantile of 0.1 is: 15.0
The quantile of 0.5 is: 35.0
The quantile 0.9 is: 85.0
