# **Numpy**

# **What is Numpy ?**
- The numpy stands for Numerical python.
- numpy is the library in python, used for mathematical calculations.
- It provide support for large multi-dimensional **arrays** and matrices.

# Data structures in numpy
**1.N-dimensional array(n-D array):**
- The n-D array have N dimensions.
- n-D array can represent Vectors(1-D array),matrices(2-D array), or tensors(3-D array).
- The n-D array are homogeneous(It contain only similar type of data).
- n-D array are have fixed size.once we created we cannot change size of this array.

**2.Structured array**:
- It is also known as **Record array**.
- structured array are heterogeneous array, i.e it stores the different types of data.

**Masked array**:
- These arrays are useful to deal with datasets contaning missing values,invalid data or placeholder.

# **Data types in structured arrays.**

**1.'i' or 'i4'**: It used as integer(int).

**2.'U10'** : It is used as a string(str).

**3. 'f' or 'f8'** : It is used as a float.

**4.'bool'** : It is used as a boolean.i.e give  output as true /false.

# **Vectors** 
- It is  one dimensional array (1-D array).

# **Matrix**
- It is also known as **2-D tensor**. i.e arrays with rows  columns.

# **Tensor**
- It is known as n-D array.i.e it have 3 or more dimensions.


# How to import numpy ?
- use **import numpy as np**

**import library**

In [12]:
import numpy as np

**Q.1 create a 2D array of shape(3,4) filled with all 1s.**

**1.ones**: ***To create an array filled with 1. mention the shape of array.(rows,column)***

In [15]:
a= np.ones((3,4)) # it craete array filled with all 1s 
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


**Q.2 create a 1D numpy array with values from 10 to 25 with a step of 4.**

**2.arange** : ***To create an array with evenly specified in the range.***

In [18]:
b=np.arange(10,25,4) # to arrange the matrix use arange(start,stop,step).create an array with  evenly specified in the range
print(b)            # it display in integer value

[10 14 18 22]


**Q.3 Create a 4x4 identity matrix.**

**3.identity** : ***It use **eye()** method To create identity matrix(specify number of rows).***


In [21]:
c=np.eye(4) # to create identity matrix(specify number of rows)
print(c)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**Q.4 create an array with 5 values evenly spaced between 0 and 1.**

**4.linspace** : ***Create an array of evenly spaced number(specified interval-(display in float)).***

In [24]:
d=np.linspace(0,1,5) # create an array of evenly spaced number(specified interval-(display in float)) linspace(start,stop,step)
print(d)

[0.   0.25 0.5  0.75 1.  ]


**Q.5 create a 1D numpy array with values from 10 to 50 with a step of 5.**

In [26]:
e=np.arange(10,50,5) # to arrange the matrix use arange(start,stop,step).create an array with  evenly specified in the range
print(e)

[10 15 20 25 30 35 40 45]


**Q.6 craete a 3X3 array with random integer between 10 and 99.** 

**5.size**: ***To give size of array.***

In [29]:
f=np.random.randint(10,99,size=(3,3)) # random.randint () use for it select number in randomly.
print(f)

[[79 57 59]
 [87 55 27]
 [90 95 38]]


**Q.7 create an array of shape(2,3) filled with zeros,and another filled with sevens.**

In [31]:
zero_array=np.zeros((2,3)) # to filled with zeros.

sevens_array=np.full((2,3),7) # full() use to filled with any number except 1 or 0
print("Zero array is:\n",zero_array)
print("Sevens array is:\n",sevens_array)

Zero array is:
 [[0. 0. 0.]
 [0. 0. 0.]]
Sevens array is:
 [[7 7 7]
 [7 7 7]]


**Q.8 Create an array with values from 1 to 12 and reshape it to a 3X4 matrix.** 

In [33]:
h=np.arange(1,13).reshape(3,4) #  reshape use for it rearrange the element to fit in new shape. 
print(h)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


**Q.9 Create a 2D array of shape (5,2) and display its attributes.**

In [35]:
p=np.random.randint(1,15,size=(5,2)) # create array it take random numbers between 1 to 15
print(p)

p.ndim # to find dimension of array
print("Dimensions of array is:",p.ndim)

p.shape # to find shape of an array
print("The shape of array is:",p.shape)

p.dtype # to get data type of elements in array
print("The Data type of array is:",p.dtype)







[[ 3 10]
 [14  7]
 [ 5  7]
 [ 2  9]
 [14  5]]
Dimensions of array is: 2
The shape of array is: (5, 2)
The Data type of array is: int32


**Q.10 create a 2D array and access its element.first element,second element , last element.**

In [37]:
x = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]]) # create 2D array

print("First row:", x[0]) # to get first element in array
print("Second column:", x[:, 1])  # to get second element in the array
print("Last element:", x[-1, -1]) # to get last elements in the array (-1 for last rows,and last column)


First row: [10 20 30]
Second column: [20 50 80]
Last element: 90


**Q.1 Create a 1D array of numbers from 0 to 9.**

In [39]:
array1=np.arange(0,9)
print(array1)

[0 1 2 3 4 5 6 7 8]


**Q.2 Find the mean, median, standard deviation, and sum of elements in an array.**

# Mathematical operation on arrays

**1.mean()**: ***To find mean(average) of all the items.***

**2.std()** : ***To find standard deviation of the all items.***

**3.median()** : ***To find median of items.***

**4.sum()**: ***To find sum(total) of all items.***

**5.min()** : ***To find minimum value in items.***

**6.max()** : ***To find maximum value in items.***

**7.argmax()** :***It return index value of max value.***

**8.argmin()** :***It return index value of min value.***

In [62]:
arr=np.array([10,20,30,40,50,60])
print(arr)

print("Mean",np.mean(arr)) # to find mean(average) of all items
print("Median :",np.std(arr)) # to find standard deviation of all items
print("standard deviation:",np.sum(arr)) # to get sum(total) of all items
print("Median:",np.median(arr)) # to get median of all items

[10 20 30 40 50 60]
Mean 35.0
Median : 17.07825127659933
standard deviation: 210
Median: 35.0


**Q.3 Find the maximum and minimum values in an array and their indices.**

In [68]:
arr=np.array([10,20,30,40,50,60])
print(arr)

print("Min:",np.min(arr)) # to get min value of items
print("Max:",np.max(arr)) # to get max value of items
 
print("Index of min value:",np.argmin(arr)) # to get index value of min value
print("Index of max value:",np.argmax(arr)) # to get index value of max value

[10 20 30 40 50 60]
Min: 10
Max: 60
Index of min value: 0
Index of max value: 5


# Random Number Methods

**1.random.randint()** : ***generate  and return an array of the given size,and the number in th range.***

**2.random.rand(size)** : ***use  return in float,it return 1D array with randomvalues in the range (0-1).***

**3.random.randn(rows,column)** : ***value range is(-infinity to +infinity)  each element mean is 0 and SD=1 .***

**Q.4 Generate a 1D array of 10 random integers between 1 and 100.**

In [71]:
random_array=np.random.randint(1,101,10) # to random number in the range
print(random_array)

[44 30 70 41 18 94 57  6 95 81]


**Q.5 Create a 3x3 array of random floats.**

In [75]:
rand_array=np.random.randn(3,3) # to get random float array it  also include negative values range value(-infinity to +infinity),randn generate and return an array with normal distribution
print(rand_array)

[[-1.64472468 -1.07971821  1.77621509]
 [-0.25807993 -0.91005662  0.61373366]
 [ 1.9914671  -0.51862446  0.97249937]]


**Q.6 Generate 1000 samples from a normal distribution and compute mean and std.**

In [82]:
sample=np.random.randn(0,1,1000)


print("Mean:",np.mean(sample))
print("Standard deviation:",np.std(sample))

Mean: nan
Standard deviation: nan


# Array manipulation

**1.np.sort()** : ***Return the sorted values in the array.default sorting is in ascending order.***

**2.np.unique()** :***Return array  an sorted with unique values.***

**3.np.concatenate()** :***Return the mergerd array, can join the two or more than two array.***


**Q.7 Get unique values from an array and their counts.**

In [88]:
a=np.array([1,2,3,4,7,5,3,4])
print(a)

print("Unique values are:",np.unique(a))


[1 2 3 4 7 5 3 4]
Unique values are: [1 2 3 4 5 7]


**Q.8 Generate a 2D array of shape (5, 5) from a normal distribution with mean=50 and std=10.**

In [95]:
mean=50
std=10
v=np.random.randn(5,5) * std + mean
print(v)

[[50.48647579 58.52790824 47.79628229 35.60139579 38.15622305]
 [39.69071467 53.40945561 39.68359384 48.27196384 50.85895038]
 [47.41798237 42.64167564 31.61763078 53.77420866 29.94269673]
 [48.58606962 16.95256112 51.81256097 62.44355222 62.0373346 ]
 [42.79644857 36.28264383 38.66270994 43.71226949 54.40520252]]


**Q.9 Create a NumPy array of even numbers from 2 to 20.**

In [98]:
even_array=np.arange(2,20,2)
print("Even array is:",even_array)

Even array is: [ 2  4  6  8 10 12 14 16 18]


**Q.10 Find the shape, size, and data type of the array a = np.array([[1, 2], [3, 4]]).**

In [107]:
a=np.array([[1,2],[3,4]])
print("Shape of array:",a.shape) # to get shape of array
print("Size of array:",a.size) # to get size of an array 
print("Data types of array:",a.dtype) # to get data types of array




Shape of array: (2, 2)
Size of array: 4
Data types of array: int32


**Q.11 Generate a 1D array of 5 random numbers between 0 and 1.**

In [116]:
random_array=np.random.rand(5) # to random number in the range
print(random_array)

[0.59733414 0.14060544 0.88917298 0.33712645 0.73508032]


**Q.12 Find the maximum, minimum, and sum of elements in the array [5, 8, 2, 9, 1].**

In [119]:
b=np.array([5, 8, 2, 9, 1])
print("maximum item:",np.max(b)) # to get maximum item
print("minimum item:",np.min(b)) # to get minimum value
print("sum of array:",np.sum(b)) # to get sum of items

maximum item: 9
minimum item: 1
sum of array: 25


**Q.13 Get the first 3 elements from the array [10, 20, 30, 40, 50].**

In [128]:
c=np.array([10,20,30,40,50])
print("First three elements are:",c[:3]) # c[:3] it return first three element in the array

First three elements are: [10 20 30]
